/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/themes/vistachase/vistachaseTheme.ts
 * Command: astryx theme build src/themes/vistachase/vistachaseTheme.ts
 * CLI: @astryxdesign/cli@0.6.5
 * Core: @astryxdesign/core@0.6.5
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const vistachaseTheme: DefinedTheme;
